set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED_tri_io[0]}]
set_property PACKAGE_PIN M17 [get_ports {GPIO_LED_tri_io[1]}]
set_property PACKAGE_PIN M19 [get_ports {GPIO_LED_tri_io[0]}]

set_property PACKAGE_PIN F16 [get_ports {GPIO_LED_tri_io[2]}]
set_property PACKAGE_PIN L19 [get_ports {GPIO_LED_tri_io[3]}]
set_property DRIVE 12 [get_ports {GPIO_LED_tri_io[3]}]
set_property PULLUP true [get_ports {GPIO_LED_tri_io[3]}]
set_property PULLUP true [get_ports {GPIO_LED_tri_io[2]}]
set_property PULLUP true [get_ports {GPIO_LED_tri_io[1]}]
set_property PULLUP true [get_ports {GPIO_LED_tri_io[0]}]
